services:
  postgres:
    image: postgres:15
    container_name: team_task_db
    restart: "no"
    environment:
      POSTGRES_DB: team_task_db
      POSTGRES_USER: guto-fn
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: laravel_pgadmin
    restart: "no"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
